const { error } = require("console");
const { axios } = require("../../utils/axios/axios");
const { ErrorWithStatus } = require("../../utils/error");

class SEOTools {
  /**
   *
   * @param {object} req
   * @param {string} req.target
   */
  async DAPACheck(req) {
    return {
      target: req.target,
      da_score: 100,
      pa_score: 100,
      spam_score: 14,
      total_backlinks: 1517349141,
    };
  }

  /**
   *
   * @param {object} req
   * @param {string} req.target
   */
  async RapidDAPACheck(req) {
    try {
      const response = await axios.get(
        "https://domain-da-pa-check.p.rapidapi.com",
        {
          params: { target: req.target },
          headers: {
            ...axios.defaults.headers,
            "X-RapidAPI-Host": "domain-da-pa-check.p.rapidapi.com",
          },
        }
      );
      if (response.data.result == "success") return response.data.body;
      else throw new ErrorWithStatus("DA/PA Request failed", response.status);
    } catch (err) {
      console.log(err);
      throw new ErrorWithStatus(
        "Something went wrong. Possibly couldn't communicate to DA/PA check service",
        500
      );
    }
  }

  /**
   * @param {string} domain
   */
  async getBacklinks(domain) {
    return backlink;
  }

  /**
   *
   * @param {object} req
   * @param {string} req.domain
   * @returns {backlink}
   */
  async RapidGetBacklinks(req) {
    try {
      const response = await axios.get(
        "https://best-backlink-checker-api.p.rapidapi.com/backlinks.php",
        {
          params: { domain: req.domain },
          headers: {
            ...axios.defaults.headers,
            "X-RapidAPI-Host": "best-backlink-checker-api.p.rapidapi.com",
          },
        }
      );
      return response.data;
    } catch (err) {
      console.log(err);
      throw new ErrorWithStatus(
        "Something went wrong. Possibly couldn't communicate to DA/PA check service",
        500
      );
    }
  }
}

module.exports = { SEOTools };

const backlink = {
  counts: {
    backlinks: {
      total: 125,
      doFollow: 35,
      fromHomePage: 0,
      doFollowFromHomePage: 0,
      text: 124,
      toHomePage: 115,
    },
    domains: {
      total: 39,
      doFollow: 22,
      fromHomePage: 0,
      toHomePage: 36,
    },
    ips: {
      total: 38,
      doFollow: 11,
    },
    cBlocks: {
      total: 33,
      doFollow: 11,
    },
    anchors: {
      total: 39,
      doFollow: 21,
    },
    anchorUrls: 8,
    topTLD: {
      line: [
        {
          label: "com",
          count: 31,
        },
        {
          label: "co",
          count: 4,
        },
        {
          label: "info",
          count: 1,
        },
      ],
    },
    topCountry: {
      line: [
        {
          code: "us",
          label: "USA",
          count: 26,
        },
        {
          code: "de",
          label: "Germany",
          count: 2,
        },
        {
          code: "fi",
          label: "Finland",
          count: 1,
        },
        {
          code: "co",
          label: "Colombia",
          count: 1,
        },
        {
          code: "lt",
          label: "Lithuania",
          count: 1,
        },
      ],
    },
    topAnchorsByBacklinks: {
      line: [
        {
          anchor: "Vconekt",
          text: true,
          count: 15,
        },
        {
          anchor: "https://vconekt.com/",
          text: true,
          count: 15,
        },
        {
          anchor: "Visit Site",
          text: true,
          count: 14,
        },
        {
          anchor: "Go to Website",
          text: true,
          count: 11,
        },
        {
          anchor: "Visit Website",
          text: true,
          count: 10,
        },
        {
          anchor: "Website",
          text: true,
          count: 7,
        },
        {
          anchor: "web design",
          text: true,
          count: 4,
        },
        {
          anchor: "creating unique website",
          text: true,
          count: 3,
        },
        {
          anchor: "developing a website",
          text: true,
          count: 3,
        },
        {
          anchor: "web development",
          text: true,
          count: 3,
        },
      ],
    },
    topAnchorsByDomains: {
      line: [
        {
          anchor: "https://vconekt.com/",
          text: true,
          count: 13,
        },
        {
          anchor: "Visit Website",
          text: true,
          count: 3,
        },
        {
          anchor: null,
          text: true,
          count: 2,
        },
        {
          anchor: "Vconekt",
          text: true,
          count: 2,
        },
        {
          anchor: "Website",
          text: true,
          count: 2,
        },
        {
          anchor: "web design",
          text: true,
          count: 2,
        },
        {
          anchor: "A Beginner's Guide to HTML and CSS",
          text: true,
          count: 1,
        },
        {
          anchor: "E-commerce",
          text: true,
          count: 1,
        },
        {
          anchor: "E-commerce marketing",
          text: true,
          count: 1,
        },
        {
          anchor: "Go to Website",
          text: true,
          count: 1,
        },
      ],
    },
    topAnchorUrlsByBacklinks: {
      line: [
        {
          label: "https://vconekt.com/",
          count: 112,
        },
        {
          label: "https://vconekt.com/ecommerce-marketing-agency/",
          count: 3,
        },
        {
          label: "https://vconekt.com/seo-consulting-services/",
          count: 3,
        },
        {
          label: "http://vconekt.com/",
          count: 2,
        },
        {
          label: "https://vconekt.com/digital-creative-agency/",
          count: 2,
        },
        {
          label: "http://www.vconekt.com/",
          count: 1,
        },
        {
          label: "https://vconekt.com/it-support-and-maintenance/",
          count: 1,
        },
        {
          label: "https://vconekt.com/organic-search-traffic/",
          count: 1,
        },
      ],
    },
    topAnchorUrlsByDomains: {
      line: [
        {
          label: "https://vconekt.com/",
          count: 31,
        },
        {
          label: "http://vconekt.com/",
          count: 1,
        },
        {
          label: "http://www.vconekt.com/",
          count: 1,
        },
        {
          label: "https://vconekt.com/digital-creative-agency/",
          count: 1,
        },
        {
          label: "https://vconekt.com/ecommerce-marketing-agency/",
          count: 1,
        },
        {
          label: "https://vconekt.com/it-support-and-maintenance/",
          count: 1,
        },
        {
          label: "https://vconekt.com/organic-search-traffic/",
          count: 1,
        },
        {
          label: "https://vconekt.com/seo-consulting-services/",
          count: 1,
        },
      ],
    },
  },
  backlinks: [
    {
      url_from: "https://clutch.co/profile/vconekt",
      url_to: "https://vconekt.com/",
      title: "Vconekt Reviews | Verified Client Reviews | Clutch.co",
      anchor: "Vconekt Logo",
      alt: "",
      nofollow: true,
      image: true,
      image_source:
        "https://img.shgstatic.com/clutch-static-prod/image/scale/50x50/s3fs-public/logos/a90d2daa297c96f65fe09c30c777375a.webp",
      inlink_rank: 23,
      domain_inlink_rank: 90,
      first_seen: "2023-11-23",
      last_visited: "2023-11-23",
    },
    {
      url_from: "https://clutch.co/profile/vconekt",
      url_to: "https://vconekt.com/",
      title: "Vconekt Reviews | Verified Client Reviews | Clutch.co",
      anchor: "Vconekt",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 23,
      domain_inlink_rank: 90,
      first_seen: "2023-11-23",
      last_visited: "2023-11-23",
    },
    {
      url_from: "https://clutch.co/profile/vconekt",
      url_to: "https://vconekt.com/",
      title: "Vconekt Reviews | Verified Client Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 23,
      domain_inlink_rank: 90,
      first_seen: "2023-11-23",
      last_visited: "2023-11-23",
    },
    {
      url_from: "https://clutch.co/pk/web-designers/ecommerce",
      url_to: "https://vconekt.com/",
      title:
        "Top E-Commerce Companies Web Designers in Pakistan - 2023 Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 18,
      domain_inlink_rank: 90,
      first_seen: "2023-01-14",
      last_visited: "2023-01-14",
    },
    {
      url_from: "https://clutch.co/pk/web-designers/real-estate",
      url_to: "https://vconekt.com/",
      title:
        "Top Real Estate Web Designers in Pakistan - 2023 Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 18,
      domain_inlink_rank: 90,
      first_seen: "2022-12-03",
      last_visited: "2023-01-03",
    },
    {
      url_from: "https://topdesignfirms.com/digital-agencies?page=38",
      url_to: "https://vconekt.com/",
      title:
        "Page 39: 100 Digital Agencies – Hire a Full Service Digital Agency",
      anchor: "Visit Site",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 12,
      domain_inlink_rank: 83,
      first_seen: "2022-12-14",
      last_visited: "2022-12-14",
    },
    {
      url_from: "https://topdesignfirms.com/digital-agencies?page=38",
      url_to: "https://vconekt.com/",
      title:
        "Page 39: 100 Digital Agencies – Hire a Full Service Digital Agency",
      anchor: "Vconekt",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 12,
      domain_inlink_rank: 83,
      first_seen: "2022-12-14",
      last_visited: "2022-12-14",
    },
    {
      url_from: "https://topdesignfirms.com/dot-net-developers?page=26",
      url_to: "https://vconekt.com/",
      title: "Page 27: 100 .NET Developers - Hire a .NET Development Company",
      anchor: "Visit Site",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 12,
      domain_inlink_rank: 83,
      first_seen: "2022-12-12",
      last_visited: "2022-12-12",
    },
    {
      url_from: "https://topdesignfirms.com/dot-net-developers?page=26",
      url_to: "https://vconekt.com/",
      title: "Page 27: 100 .NET Developers - Hire a .NET Development Company",
      anchor: "Vconekt",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 12,
      domain_inlink_rank: 83,
      first_seen: "2022-12-12",
      last_visited: "2022-12-12",
    },
    {
      url_from: "https://topdesignfirms.com/web-design/wordpress?page=26",
      url_to: "https://vconekt.com/",
      title: "Page 27: 100 WordPress Web Design Companies",
      anchor: "Visit Site",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 12,
      domain_inlink_rank: 83,
      first_seen: "2022-10-29",
      last_visited: "2022-12-10",
    },
    {
      url_from:
        "http://webproxy.stealthy.co/index.php?q=https://clutch.co/pk/developers/ecommerce",
      url_to: "https://vconekt.com/",
      title: "Top E-Commerce Developers in Pakistan - 2022 Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 7,
      domain_inlink_rank: 63,
      first_seen: "2022-07-29",
      last_visited: "2022-07-29",
    },
    {
      url_from:
        "http://webproxy.stealthy.co/index.php?q=https://clutch.co/pk/seo-firms/leaders-matrix",
      url_to: "https://vconekt.com/",
      title: "Top Pakistan SEO Services Companies - 2022 Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 7,
      domain_inlink_rank: 63,
      first_seen: "2022-07-29",
      last_visited: "2022-07-29",
    },
    {
      url_from:
        "http://webproxy.stealthy.co/index.php?q=https://clutch.co/pk/seo-firms",
      url_to: "https://vconekt.com/",
      title: "Top SEO Companies in Pakistan - 2022 Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 7,
      domain_inlink_rank: 63,
      first_seen: "2022-07-29",
      last_visited: "2022-07-29",
    },
    {
      url_from:
        "http://webproxy.stealthy.co/index.php?q=https://clutch.co/pk/web-designers/leaders-matrix",
      url_to: "https://vconekt.com/",
      title: "Top Pakistan Web Designers - 2022 Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 7,
      domain_inlink_rank: 63,
      first_seen: "2022-07-29",
      last_visited: "2022-07-29",
    },
    {
      url_from:
        "http://webproxy.stealthy.co/index.php?q=https://clutch.co/pk/web-designers",
      url_to: "https://vconekt.com/",
      title: "Top Web Designers in Pakistan - 2022 Reviews | Clutch.co",
      anchor: "Visit Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 7,
      domain_inlink_rank: 63,
      first_seen: "2022-07-29",
      last_visited: "2022-07-29",
    },
    {
      url_from:
        "https://enkling.com/read-blog/29301_unveiling-the-power-of-seo-services.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "Unveiling the Power of SEO Services",
      anchor: "Understanding SEO Services",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 6,
      domain_inlink_rank: 51,
      first_seen: "2023-09-09",
      last_visited: "2023-09-09",
    },
    {
      url_from:
        "https://enkling.com/read-blog/29301_unveiling-the-power-of-seo-services.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "Unveiling the Power of SEO Services",
      anchor: "business,",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 6,
      domain_inlink_rank: 51,
      first_seen: "2023-09-09",
      last_visited: "2023-09-09",
    },
    {
      url_from:
        "https://enkling.com/read-blog/29301_unveiling-the-power-of-seo-services.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "Unveiling the Power of SEO Services",
      anchor: "high-quality conten",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 6,
      domain_inlink_rank: 51,
      first_seen: "2023-09-09",
      last_visited: "2023-09-09",
    },
    {
      url_from:
        "https://enkling.com/read-blog/29301_unveiling-the-power-of-seo-services.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "Unveiling the Power of SEO Services",
      anchor: "optimizing landing pages",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 6,
      domain_inlink_rank: 51,
      first_seen: "2023-09-09",
      last_visited: "2023-09-09",
    },
    {
      url_from:
        "https://enkling.com/read-blog/29301_unveiling-the-power-of-seo-services.html",
      url_to: "https://vconekt.com/",
      title: "Unveiling the Power of SEO Services",
      anchor: "Understanding SEO Services",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 6,
      domain_inlink_rank: 51,
      first_seen: "2023-09-03",
      last_visited: "2023-09-03",
    },
    {
      url_from: "https://indibloghub.com/profile/vconekt9",
      url_to: "https://vconekt.com/",
      title: "Vconekt (@vconekt9) | IndiBlogHub",
      anchor: "",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 5,
      domain_inlink_rank: 46,
      first_seen: "2023-11-29",
      last_visited: "2023-11-29",
    },
    {
      url_from:
        "https://indibloghub.com/post/ecommerce-marketing-agency-driving-success-in-the-online-marketplace",
      url_to: "https://vconekt.com/ecommerce-marketing-agency/",
      title:
        "Ecommerce Marketing Agency: Driving Success in the Online Marketplace",
      anchor: "marketing",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 5,
      domain_inlink_rank: 46,
      first_seen: "2023-10-09",
      last_visited: "2023-10-09",
    },
    {
      url_from:
        "https://indibloghub.com/post/ecommerce-marketing-agency-driving-success-in-the-online-marketplace",
      url_to: "https://vconekt.com/ecommerce-marketing-agency/",
      title:
        "Ecommerce Marketing Agency: Driving Success in the Online Marketplace",
      anchor: "E-commerce",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 5,
      domain_inlink_rank: 46,
      first_seen: "2023-10-09",
      last_visited: "2023-10-09",
    },
    {
      url_from:
        "https://indibloghub.com/post/ecommerce-marketing-agency-driving-success-in-the-online-marketplace",
      url_to: "https://vconekt.com/ecommerce-marketing-agency/",
      title:
        "Ecommerce Marketing Agency: Driving Success in the Online Marketplace",
      anchor: "E-commerce marketing",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 5,
      domain_inlink_rank: 46,
      first_seen: "2023-10-09",
      last_visited: "2023-10-09",
    },
    {
      url_from:
        "https://www.upvotes.co/mobile-application-developers/federal-capital-area",
      url_to: "https://vconekt.com/",
      title:
        "Top Mobile App Developers in federal capital area- 2022 | upvotes.co",
      anchor: "Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 4,
      domain_inlink_rank: 37,
      first_seen: "2022-05-28",
      last_visited: "2022-10-11",
    },
    {
      url_from: "https://www.upvotes.co/mobile-application-developers/pakistan",
      url_to: "https://vconekt.com/",
      title: "Top Mobile App Developers in pakistan- 2022 | upvotes.co",
      anchor: "Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 4,
      domain_inlink_rank: 37,
      first_seen: "2022-05-28",
      last_visited: "2022-10-11",
    },
    {
      url_from:
        "https://www.upvotes.co/mobile-application-developers/rawalpindi",
      url_to: "https://vconekt.com/",
      title: "Top Mobile App Developers in rawalpindi- 2022 | upvotes.co",
      anchor: "Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 4,
      domain_inlink_rank: 37,
      first_seen: "2022-05-28",
      last_visited: "2022-10-11",
    },
    {
      url_from:
        "https://upvotes.co/mobile-application-developers/federal-capital-area",
      url_to: "https://vconekt.com/",
      title:
        "Top Mobile App Developers in federal capital area- 2023 | upvotes.co",
      anchor: "Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 2,
      domain_inlink_rank: 37,
      first_seen: "2023-11-19",
      last_visited: "2023-11-19",
    },
    {
      url_from: "https://upvotes.co/mobile-application-developers/pakistan",
      url_to: "https://vconekt.com/",
      title: "Top Mobile App Developers in pakistan- 2023 | upvotes.co",
      anchor: "Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 2,
      domain_inlink_rank: 37,
      first_seen: "2023-11-19",
      last_visited: "2023-11-19",
    },
    {
      url_from:
        "https://topitcompanies.co/categories/ecommerce-developers/ke/state/busia",
      url_to: "https://vconekt.com/",
      title: "Top 10+ E-Commerce Development Companies in Busia 2023",
      anchor: "Go to Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 41,
      first_seen: "2023-11-22",
      last_visited: "2023-11-22",
    },
    {
      url_from: "https://www.aqlisting.com/listing/vconekt",
      url_to: "https://vconekt.com/",
      title: "Vconekt - AQlisting",
      anchor: "",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 1,
      first_seen: "2023-04-06",
      last_visited: "2023-05-03",
    },
    {
      url_from: "http://aqlisting.com/listing/vconekt/",
      url_to: "https://vconekt.com/",
      title: "Vconekt – AQ Listing – Free business Directory",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 1,
      first_seen: "2022-08-22",
      last_visited: "2022-08-22",
    },
    {
      url_from: "https://aqlisting.com/listing/vconekt/",
      url_to: "https://vconekt.com/",
      title: "Vconekt - AQ Listing - Free business Directory",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 1,
      first_seen: "2022-09-06",
      last_visited: "2022-11-23",
    },
    {
      url_from:
        "https://erozighar.com/job/vconekt-nust-office-1302-sector-h-12-nstp-islamabad-44000-full-time-office-based-php-laravel-developer/",
      url_to: "https://vconekt.com/",
      title: "PHP / Laravel Developer | Erozighar",
      anchor: "Job Description:",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 1,
      first_seen: "2021-08-12",
      last_visited: "2021-08-12",
    },
    {
      url_from:
        "https://erozighar.com/job/vconekt-nust-office-1302-sector-h-12-nstp-islamabad-44000-full-time-office-based-php-laravel-developer/",
      url_to: "https://vconekt.com/",
      title: "PHP / Laravel Developer | Erozighar",
      anchor: "Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 1,
      first_seen: "2021-08-12",
      last_visited: "2021-08-12",
    },
    {
      url_from: "https://cityoftips.com/2023/06/08/digital-creative-agency/",
      url_to: "https://vconekt.com/digital-creative-agency/",
      title: "DIGITAL CREATIVE AGENCY - CityofTips",
      anchor: "digital creative agency",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 22,
      first_seen: "2023-11-06",
      last_visited: "2023-11-06",
    },
    {
      url_from: "https://cityoftips.com/2023/06/08/digital-creative-agency/",
      url_to: "https://vconekt.com/digital-creative-agency/",
      title: "DIGITAL CREATIVE AGENCY - CityofTips",
      anchor: "Social media",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 1,
      domain_inlink_rank: 22,
      first_seen: "2023-11-06",
      last_visited: "2023-11-06",
    },
    {
      url_from:
        "https://topitcompanies.co/categories/blockchain-developers/id/city/kabupaten-raja-ampat",
      url_to: "https://vconekt.com/",
      title:
        "Top 10+ Blockchain Development Companies in Kabupaten Raja Ampat 2023",
      anchor: "Go to Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 41,
      first_seen: "2023-11-27",
      last_visited: "2023-11-27",
    },
    {
      url_from:
        "https://topitcompanies.co/categories/c-sharp/web-developers/cu/state/camagueey-province",
      url_to: "https://vconekt.com/",
      title: "Top 10+ C-sharp Development Companies in Camagueey Province 2023",
      anchor: "Go to Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 41,
      first_seen: "2023-12-08",
      last_visited: "2023-12-08",
    },
    {
      url_from:
        "https://topitcompanies.co/categories/cakephp/web-developers/ng/state/ondo",
      url_to: "https://vconekt.com/",
      title: "Top 10+ Cakephp Development Companies in Ondo 2023",
      anchor: "Go to Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 41,
      first_seen: "2023-11-27",
      last_visited: "2023-11-27",
    },
    {
      url_from:
        "https://topitcompanies.co/categories/codeigniter/web-developers/ug/state/kyankwanzi-district",
      url_to: "https://vconekt.com/",
      title:
        "Top 10+ Codeigniter Development Companies in Kyankwanzi District 2023",
      anchor: "Go to Website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 41,
      first_seen: "2023-12-03",
      last_visited: "2023-12-03",
    },
    {
      url_from:
        "http://adbellmedia.com/posts/web-design-for-a-global-audience-multilingual-considerations",
      url_to: "https://vconekt.com/",
      title:
        "Adbell Media - Web Design for a Global Audience: Multilingual Considerations",
      anchor: "websites we design",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 49,
      first_seen: "2023-11-20",
      last_visited: "2023-11-20",
    },
    {
      url_from:
        "https://adbellmedia.com/posts/web-design-for-a-global-audience-multilingual-considerations",
      url_to: "https://vconekt.com/",
      title:
        "Adbell Media - Web Design for a Global Audience: Multilingual Considerations",
      anchor: "websites we design",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 49,
      first_seen: "2023-11-27",
      last_visited: "2023-11-27",
    },
    {
      url_from:
        "http://adbellmedia.com/posts/web-design-for-a-global-audience-multilingual-considerations",
      url_to: "https://vconekt.com/",
      title:
        "Adbell Media - Web Design for a Global Audience: Multilingual Considerations",
      anchor: "developing a website",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 49,
      first_seen: "2023-11-20",
      last_visited: "2023-11-20",
    },
    {
      url_from:
        "https://adbellmedia.com/posts/web-design-for-a-global-audience-multilingual-considerations",
      url_to: "https://vconekt.com/",
      title:
        "Adbell Media - Web Design for a Global Audience: Multilingual Considerations",
      anchor: "developing a website",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 49,
      first_seen: "2023-11-27",
      last_visited: "2023-11-27",
    },
    {
      url_from:
        "https://adbellmedia.com/public/posts/web-design-for-a-global-audience-multilingual-considerations",
      url_to: "https://vconekt.com/",
      title:
        "Adbell Media - Web Design for a Global Audience: Multilingual Considerations",
      anchor: "websites we design",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 49,
      first_seen: "2023-12-10",
      last_visited: "2023-12-10",
    },
    {
      url_from:
        "https://bestbacklinkseo.com/page/digital-services/the-best-digital-marketing-agency",
      url_to: "https://vconekt.com/",
      title:
        "The best digital marketing agency | Digital Services - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-12-08",
      last_visited: "2023-12-08",
    },
    {
      url_from:
        "https://bestbookmarkpoint.com/page/digital-marketing/the-best-digital-marketing-agency-which-provides-best-digital-services-",
      url_to: "https://vconekt.com/",
      title:
        "The Best Digital Marketing Agency Which Provides Best digital Services . | Digital Marketing - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-11-15",
      last_visited: "2023-11-15",
    },
    {
      url_from:
        "https://bookmarkseolink.com/page/digital-marketing/the-best-digital-marketing-services-provider",
      url_to: "https://vconekt.com/",
      title:
        "The Best Digital Marketing Services Provider | Digital Marketing - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-11-16",
      last_visited: "2023-11-16",
    },
    {
      url_from: "https://findbestserver.com/index.php/tag/web-design/",
      url_to: "https://vconekt.com/",
      title: "web design – Find Best Dedicated Server | VPS | Web Hosting",
      anchor: "Responsive websites",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 33,
      first_seen: "2023-12-02",
      last_visited: "2023-12-02",
    },
    {
      url_from: "https://findbestserver.com/index.php/tag/web-design/",
      url_to: "https://vconekt.com/",
      title: "web design – Find Best Dedicated Server | VPS | Web Hosting",
      anchor: "web design",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 33,
      first_seen: "2023-12-02",
      last_visited: "2023-12-02",
    },
    {
      url_from:
        "https://freedost.com/read-blog/632_creating-unique-website-interactions.html",
      url_to: "https://vconekt.com/",
      title: "Creating Unique Website Interactions",
      anchor: "website's success",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 36,
      first_seen: "2023-11-26",
      last_visited: "2023-11-26",
    },
    {
      url_from:
        "https://freedost.com/read-blog/632_creating-unique-website-interactions.html?mode=day",
      url_to: "https://vconekt.com/",
      title: "Creating Unique Website Interactions",
      anchor: "website's success",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 36,
      first_seen: "2023-12-06",
      last_visited: "2023-12-06",
    },
    {
      url_from:
        "https://freedost.com/read-blog/632_creating-unique-website-interactions.html?mode=day",
      url_to: "https://vconekt.com/",
      title: "Creating Unique Website Interactions",
      anchor: "creating unique website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 36,
      first_seen: "2023-12-06",
      last_visited: "2023-12-06",
    },
    {
      url_from:
        "https://freedost.com/read-blog/632_creating-unique-website-interactions.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "Creating Unique Website Interactions",
      anchor: "website's success",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 36,
      first_seen: "2023-11-30",
      last_visited: "2023-11-30",
    },
    {
      url_from:
        "https://freedost.com/read-blog/632_creating-unique-website-interactions.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "Creating Unique Website Interactions",
      anchor: "creating unique website",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 36,
      first_seen: "2023-11-30",
      last_visited: "2023-11-30",
    },
    {
      url_from:
        "https://freeseoqualitybookmarking.com/page/digital-services/the-best-digital-services-providers",
      url_to: "https://vconekt.com/",
      title:
        "The best digital services providers | Digital Services - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-12-03",
      last_visited: "2023-12-03",
    },
    {
      url_from:
        "https://havily.com/ensuring-seamless-operations-the-role-of-it-support-and-maintenance/",
      url_to: "https://vconekt.com/",
      title:
        "Ensuring Seamless Operations: The Role of IT Support and Maintenance - Havily",
      anchor: "boosting",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 47,
      first_seen: "2023-11-22",
      last_visited: "2023-11-22",
    },
    {
      url_from:
        "https://highdabookmark.com/page/digital-services/the-best-digital-marketing-services-provider",
      url_to: "https://vconekt.com/",
      title:
        "The best digital marketing services provider | Digital Services - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-12-11",
      last_visited: "2023-12-11",
    },
    {
      url_from:
        "https://www.hotbookmarking.com/the-art-of-crafting-seo-friendly-web-design/",
      url_to: "https://vconekt.com/",
      title:
        "The Art of Crafting SEO-Friendly Web Design – Social Network to Advertise Your Site and Business Content",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 32,
      first_seen: "2023-11-06",
      last_visited: "2023-11-06",
    },
    {
      url_from:
        "https://www.hotbookmarking.com/web-design-psychology-understanding-user-behavior/",
      url_to: "https://vconekt.com/",
      title:
        "Web Design Psychology: Understanding User Behavior – Social Network to Advertise Your Site and Business Content",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 32,
      first_seen: "2023-11-06",
      last_visited: "2023-11-06",
    },
    {
      url_from:
        "https://kyourc.com/read-blog/3874_the-evolution-of-web-design-from-flash-to-html5.html",
      url_to: "https://vconekt.com/",
      title: "The Evolution of Web Design: From Flash to HTML5",
      anchor: "web development",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 65,
      first_seen: "2023-11-28",
      last_visited: "2023-11-28",
    },
    {
      url_from:
        "https://kyourc.com/read-blog/3874_the-evolution-of-web-design-from-flash-to-html5.html?mode=day",
      url_to: "https://vconekt.com/",
      title: "The Evolution of Web Design: From Flash to HTML5",
      anchor: "web development",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 65,
      first_seen: "2023-12-10",
      last_visited: "2023-12-10",
    },
    {
      url_from:
        "https://kyourc.com/read-blog/3874_the-evolution-of-web-design-from-flash-to-html5.html?mode=day",
      url_to: "https://vconekt.com/",
      title: "The Evolution of Web Design: From Flash to HTML5",
      anchor: "web design",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 65,
      first_seen: "2023-12-10",
      last_visited: "2023-12-10",
    },
    {
      url_from:
        "https://kyourc.com/read-blog/3874_the-evolution-of-web-design-from-flash-to-html5.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "The Evolution of Web Design: From Flash to HTML5",
      anchor: "web development",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 65,
      first_seen: "2023-12-02",
      last_visited: "2023-12-02",
    },
    {
      url_from:
        "https://kyourc.com/read-blog/3874_the-evolution-of-web-design-from-flash-to-html5.html?mode=night",
      url_to: "https://vconekt.com/",
      title: "The Evolution of Web Design: From Flash to HTML5",
      anchor: "web design",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 65,
      first_seen: "2023-12-02",
      last_visited: "2023-12-02",
    },
    {
      url_from:
        "https://linkspreed.com/read-blog/59215_web-animation-enhancing-engagement-and-storytelling.html",
      url_to: "https://vconekt.com/",
      title: "Web Animation: Enhancing Engagement and Storytelling",
      anchor: "web design & development",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 84,
      first_seen: "2023-10-19",
      last_visited: "2023-10-19",
    },
    {
      url_from:
        "https://linkspreed.com/read-blog/59215_web-animation-enhancing-engagement-and-storytelling.html",
      url_to: "https://vconekt.com/",
      title: "Web Animation: Enhancing Engagement and Storytelling",
      anchor: "Web animation",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 84,
      first_seen: "2023-10-19",
      last_visited: "2023-10-19",
    },
    {
      url_from:
        "https://newseodofollow.com/page/digital-marketing/the-best-digital-marketing-services-provider",
      url_to: "https://vconekt.com/",
      title:
        "The Best Digital Marketing Services Provider | Digital Marketing - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-11-16",
      last_visited: "2023-11-16",
    },
    {
      url_from:
        "https://www.onlinewebmarks.com/the-art-of-crafting-seo-friendly-web-design/",
      url_to: "https://vconekt.com/",
      title:
        "The Art of Crafting SEO-Friendly Web Design – Internet Driven SEO System for Submitting Business Content",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 38,
      first_seen: "2023-12-07",
      last_visited: "2023-12-07",
    },
    {
      url_from:
        "https://readnewsblog.com/the-role-of-typography-in-modern-web-design/",
      url_to: "https://vconekt.com/",
      title: "The Role of Typography in Modern Web Design - Read News Blog",
      anchor: "modern web design",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 46,
      first_seen: "2023-11-19",
      last_visited: "2023-11-19",
    },
    {
      url_from:
        "https://seobacklinkpoint.com/page/digital-services/the-best-digital-marketing-agency",
      url_to: "https://vconekt.com/",
      title:
        "The best digital marketing agency | Digital Services - SEO Backlink Point",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-12-03",
      last_visited: "2023-12-03",
    },
    {
      url_from:
        "https://seopointsubmission.com/page/digital-marketing/the-best-digital-marketing-services-provider-",
      url_to: "https://vconekt.com/",
      title:
        "The Best Digital Marketing Services Provider. | Digital Marketing - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-11-18",
      last_visited: "2023-11-18",
    },
    {
      url_from:
        "https://theseobacklink.com/detail/a-beginners-guide-to-html-and-css53064",
      url_to: "https://vconekt.com/",
      title: "A Beginner's Guide to HTML and CSS- theseobacklink.com",
      anchor: "A Beginner's Guide to HTML and CSS",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 37,
      first_seen: "2023-11-20",
      last_visited: "2023-11-20",
    },
    {
      url_from:
        "https://www.theseobacklink.com/detail/a-beginners-guide-to-html-and-css53064",
      url_to: "https://vconekt.com/",
      title: "A Beginner's Guide to HTML and CSS- theseobacklink.com",
      anchor: "A Beginner's Guide to HTML and CSS",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 37,
      first_seen: "2023-11-22",
      last_visited: "2023-11-22",
    },
    {
      url_from:
        "https://timesofrising.com/revolutionizing-e-commerce-with-progressive-web-apps/",
      url_to: "https://vconekt.com/",
      title:
        "Revolutionizing E-Commerce With Progressive Web Apps - TIMES OF RISING",
      anchor: "web technology",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 48,
      first_seen: "2023-10-28",
      last_visited: "2023-10-28",
    },
    {
      url_from:
        "https://timesofrising.com/revolutionizing-e-commerce-with-progressive-web-apps/",
      url_to: "https://vconekt.com/",
      title:
        "Revolutionizing E-Commerce With Progressive Web Apps - TIMES OF RISING",
      anchor: "web applications",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 48,
      first_seen: "2023-10-28",
      last_visited: "2023-10-28",
    },
    {
      url_from:
        "https://topseosbmservice.com/page/digital-services/the-best-digital-marketing-services-",
      url_to: "https://vconekt.com/",
      title:
        "The best digital marketing services | Digital Services - FB Bookmark",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-12-08",
      last_visited: "2023-12-08",
    },
    {
      url_from: "https://topwebdevelopersnetwork.com/companies/asia/islamabad",
      url_to: "https://vconekt.com/",
      title: "Top 10+ Web Development Companies In Islamabad (2022)",
      anchor: "Visit Website",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 18,
      first_seen: "2023-01-14",
      last_visited: "2023-01-14",
    },
    {
      url_from: "http://www.websitescrawl.com/domain-list-22186",
      url_to: "http://vconekt.com/",
      title: "WebsitesCrawl.com | Most Used Websites | page No. 22186",
      anchor: "vconekt",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 74,
      first_seen: "2023-11-19",
      last_visited: "2023-11-19",
    },
    {
      url_from: "https://www.websitescrawl.com/domain-list-22186",
      url_to: "http://vconekt.com/",
      title: "WebsitesCrawl.com | Most Used Websites | page No. 22186",
      anchor: "vconekt",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 74,
      first_seen: "2023-11-20",
      last_visited: "2023-11-20",
    },
    {
      url_from: "https://www.yellowpagesnepal.com/vconekt",
      url_to: "http://www.vconekt.com/",
      title: "VConeKt",
      anchor: "http://www.vconekt.com/",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 48,
      first_seen: "2023-11-26",
      last_visited: "2023-11-26",
    },
    {
      url_from:
        "https://www.bsocialbookmarking.info/web-design-and-seo-a-symbiotic-relationship/",
      url_to: "https://vconekt.com/",
      title:
        "Web Design and SEO: A Symbiotic Relationship – Most Popular Social Bookmarking Site to Boost SEO Content",
      anchor: "https://vconekt.com/",
      alt: "",
      nofollow: true,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 30,
      first_seen: "2023-10-19",
      last_visited: "2023-10-19",
    },
    {
      url_from:
        "https://havily.com/ensuring-seamless-operations-the-role-of-it-support-and-maintenance/",
      url_to: "https://vconekt.com/it-support-and-maintenance/",
      title:
        "Ensuring Seamless Operations: The Role of IT Support and Maintenance - Havily",
      anchor: "IT Support and Maintenance,",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 47,
      first_seen: "2023-11-22",
      last_visited: "2023-11-22",
    },
    {
      url_from:
        "https://freedofollowwebsite.com/page/digital-services/organic-search-traffic",
      url_to: "https://vconekt.com/organic-search-traffic/",
      title:
        "Organic Search Traffic | Digital Services - Free Do-Follow Website",
      anchor: "https://vconekt.com/organic-search-traffic/",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 4,
      first_seen: "2023-11-17",
      last_visited: "2023-11-17",
    },
    {
      url_from: "https://prodealtimes.com/category/digital-marketing/page/3/",
      url_to: "https://vconekt.com/seo-consulting-services/",
      title: "Digital Marketing | prodealtimes.com",
      anchor: "SEO consulting",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 21,
      first_seen: "2023-11-29",
      last_visited: "2023-11-29",
    },
    {
      url_from: "https://prodealtimes.com/category/digital-marketing/page/3/",
      url_to: "https://vconekt.com/seo-consulting-services/",
      title: "Digital Marketing | prodealtimes.com",
      anchor: "SEO",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 21,
      first_seen: "2023-11-29",
      last_visited: "2023-11-29",
    },
    {
      url_from: "https://prodealtimes.com/category/digital-marketing/page/3/",
      url_to: "https://vconekt.com/seo-consulting-services/",
      title: "Digital Marketing | prodealtimes.com",
      anchor: "SEO consulting services",
      alt: "",
      nofollow: false,
      image: false,
      image_source: "",
      inlink_rank: 0,
      domain_inlink_rank: 21,
      first_seen: "2023-11-29",
      last_visited: "2023-11-29",
    },
  ],
};
