const keywordsByWebsite = {
  result: {
    keywords: [
      {
        keyword: "smtp server tester",
        topRankedUrl: "https://promoterkit.com/tools/email/smtp-tester",
        rank: 57,
        rankChange: null,
        searchVolume: 50,
        rankingHomepages: 2,
        paidCompetitors: 1,
      },
      {
        keyword: "online seo analysis report",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 55,
        rankChange: 17,
        searchVolume: 50,
        rankingHomepages: 8,
        paidCompetitors: 7,
      },
      {
        keyword: "seo analyze tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 51,
        rankChange: -16,
        searchVolume: 50,
        rankingHomepages: 11,
        paidCompetitors: 4,
      },
      {
        keyword: "email validation tool free",
        topRankedUrl: "https://promoterkit.com/tools/email/bulk-verifier",
        rank: 46,
        rankChange: -6,
        searchVolume: 50,
        rankingHomepages: 20,
        paidCompetitors: 0,
      },
      {
        keyword: "keyword tool gratis",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 85,
        rankChange: 11,
        searchVolume: 50,
        rankingHomepages: 22,
        paidCompetitors: 2,
      },
      {
        keyword: "tags finder youtube",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 46,
        rankChange: 6,
        searchVolume: 50,
        rankingHomepages: 6,
        paidCompetitors: 0,
      },
      {
        keyword: "check backlinks website",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 43,
        rankChange: 0,
        searchVolume: 50,
        rankingHomepages: 2,
        paidCompetitors: 0,
      },
      {
        keyword: "free email verifier tool",
        topRankedUrl: "https://promoterkit.com/tools/email/bulk-verifier",
        rank: 48,
        rankChange: null,
        searchVolume: 50,
        rankingHomepages: 14,
        paidCompetitors: 0,
      },
      {
        keyword: "keywords tool free",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 86,
        rankChange: -6,
        searchVolume: 50,
        rankingHomepages: 12,
        paidCompetitors: 1,
      },
      {
        keyword: "kit ai",
        topRankedUrl: "https://promoterkit.com/tools/ai/",
        rank: 86,
        rankChange: null,
        searchVolume: 50,
        rankingHomepages: 24,
        paidCompetitors: 0,
      },
      {
        keyword: "name youtube generator",
        topRankedUrl: "https://promoterkit.com/tools/youtube/name-generator",
        rank: 89,
        rankChange: null,
        searchVolume: 50,
        rankingHomepages: 1,
        paidCompetitors: 0,
      },
      {
        keyword: "check backlink profile",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 56,
        rankChange: -5,
        searchVolume: 50,
        rankingHomepages: 2,
        paidCompetitors: 0,
      },
      {
        keyword: "seo analyzer tool online",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 27,
        rankChange: -3,
        searchVolume: 50,
        rankingHomepages: 14,
        paidCompetitors: 7,
      },
      {
        keyword: "keywords generator online free",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 73,
        rankChange: -9,
        searchVolume: 55,
        rankingHomepages: 12,
        paidCompetitors: 1,
      },
      {
        keyword: "free seo keywords generator",
        topRankedUrl: "https://promoterkit.com/tools/seo/keyword-research",
        rank: 64,
        rankChange: -3,
        searchVolume: 55,
        rankingHomepages: 10,
        paidCompetitors: 0,
      },
      {
        keyword: "keyword creator free",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 74,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 13,
        paidCompetitors: 0,
      },
      {
        keyword: "essay outline online",
        topRankedUrl: "https://promoterkit.com/tools/ai/outline-generator",
        rank: 44,
        rankChange: 2,
        searchVolume: 55,
        rankingHomepages: 10,
        paidCompetitors: 4,
      },
      {
        keyword: "seo tools keyword generator",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 81,
        rankChange: -4,
        searchVolume: 55,
        rankingHomepages: 9,
        paidCompetitors: 0,
      },
      {
        keyword: "outline of tools",
        topRankedUrl: "https://promoterkit.com/tools/ai/outline-generator",
        rank: 53,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 3,
        paidCompetitors: 0,
      },
      {
        keyword: "spam subject line tester",
        topRankedUrl: "https://promoterkit.com/tools/email/subject-line-tester",
        rank: 30,
        rankChange: 1,
        searchVolume: 55,
        rankingHomepages: 3,
        paidCompetitors: 2,
      },
      {
        keyword: "seo back link checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 70,
        rankChange: 0,
        searchVolume: 55,
        rankingHomepages: 3,
        paidCompetitors: 1,
      },
      {
        keyword: "free website backlink checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 35,
        rankChange: 0,
        searchVolume: 55,
        rankingHomepages: 2,
        paidCompetitors: 6,
      },
      {
        keyword: "best keywords for youtube channel",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 102,
        rankChange: -17,
        searchVolume: 55,
        rankingHomepages: 0,
        paidCompetitors: 0,
      },
      {
        keyword: "youtube keywordtool",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 18,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 1,
        paidCompetitors: 0,
      },
      {
        keyword: "seo analysis online tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 34,
        rankChange: 11,
        searchVolume: 55,
        rankingHomepages: 13,
        paidCompetitors: 2,
      },
      {
        keyword: "outline generator for research paper",
        topRankedUrl: "https://promoterkit.com/tools/ai/outline-generator",
        rank: 27,
        rankChange: -9,
        searchVolume: 55,
        rankingHomepages: 1,
        paidCompetitors: 0,
      },
      {
        keyword: "backlink tester",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 54,
        rankChange: -10,
        searchVolume: 55,
        rankingHomepages: 4,
        paidCompetitors: 5,
      },
      {
        keyword: "backlinks free checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 36,
        rankChange: -6,
        searchVolume: 55,
        rankingHomepages: 3,
        paidCompetitors: 1,
      },
      {
        keyword: "smtp test utility",
        topRankedUrl: "https://promoterkit.com/tools/email/smtp-tester",
        rank: 34,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 4,
        paidCompetitors: 0,
      },
      {
        keyword: "page seo analyzer",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 50,
        rankChange: -7,
        searchVolume: 55,
        rankingHomepages: 16,
        paidCompetitors: 4,
      },
      {
        keyword: "check email list for bounces free",
        topRankedUrl: "https://promoterkit.com/tools/email/bulk-verifier",
        rank: 35,
        rankChange: -13,
        searchVolume: 55,
        rankingHomepages: 16,
        paidCompetitors: 4,
      },
      {
        keyword: "keywords research free",
        topRankedUrl: "https://promoterkit.com/tools/seo/keyword-research",
        rank: 67,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 11,
        paidCompetitors: 0,
      },
      {
        keyword: "free backlinks check",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 37,
        rankChange: -7,
        searchVolume: 55,
        rankingHomepages: 2,
        paidCompetitors: 0,
      },
      {
        keyword: "backlinks tool checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 59,
        rankChange: -34,
        searchVolume: 55,
        rankingHomepages: 8,
        paidCompetitors: 0,
      },
      {
        keyword: "email address validator online",
        topRankedUrl: "https://promoterkit.com/tools/email/checker",
        rank: 77,
        rankChange: 2,
        searchVolume: 55,
        rankingHomepages: 17,
        paidCompetitors: 0,
      },
      {
        keyword: "backlink checker online free",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 37,
        rankChange: -4,
        searchVolume: 55,
        rankingHomepages: 4,
        paidCompetitors: 2,
      },
      {
        keyword: "bulk check keyword competition",
        topRankedUrl: "https://promoterkit.com/tools/seo/bulk-keyword-tool",
        rank: 17,
        rankChange: -4,
        searchVolume: 55,
        rankingHomepages: 7,
        paidCompetitors: 1,
      },
      {
        keyword: "content writing tools online free",
        topRankedUrl: "https://promoterkit.com/tools/ai/writer",
        rank: 90,
        rankChange: -41,
        searchVolume: 55,
        rankingHomepages: 4,
        paidCompetitors: 14,
      },
      {
        keyword: "privacy policy generater",
        topRankedUrl:
          "https://promoterkit.com/tools/web/privacy-policy-generator",
        rank: 48,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 10,
        paidCompetitors: 0,
      },
      {
        keyword: "outline ai",
        topRankedUrl: "https://promoterkit.com/tools/ai/outline-generator",
        rank: 22,
        rankChange: 8,
        searchVolume: 55,
        rankingHomepages: 2,
        paidCompetitors: 0,
      },
      {
        keyword: "free backlink analysis",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 35,
        rankChange: -5,
        searchVolume: 55,
        rankingHomepages: 2,
        paidCompetitors: 1,
      },
      {
        keyword: "keyword search count tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/bulk-keyword-tool",
        rank: 77,
        rankChange: -10,
        searchVolume: 55,
        rankingHomepages: 7,
        paidCompetitors: 1,
      },
      {
        keyword: "free seo analysis of a website",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 55,
        rankChange: 5,
        searchVolume: 55,
        rankingHomepages: 17,
        paidCompetitors: 2,
      },
      {
        keyword: "youtube ranking tool",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 51,
        rankChange: -5,
        searchVolume: 55,
        rankingHomepages: 7,
        paidCompetitors: 2,
      },
      {
        keyword: "free backlink analysis tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 55,
        rankChange: -13,
        searchVolume: 55,
        rankingHomepages: 3,
        paidCompetitors: 1,
      },
      {
        keyword: "bulk email verify",
        topRankedUrl: "https://promoterkit.com/tools/email/bulk-verifier",
        rank: 37,
        rankChange: 2,
        searchVolume: 55,
        rankingHomepages: 18,
        paidCompetitors: 12,
      },
      {
        keyword: "text email extractor",
        topRankedUrl: "https://promoterkit.com/tools/email/text-extraction",
        rank: 16,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 6,
        paidCompetitors: 0,
      },
      {
        keyword: "backlink checker website",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 41,
        rankChange: -22,
        searchVolume: 55,
        rankingHomepages: 5,
        paidCompetitors: 1,
      },
      {
        keyword: "youtube title keywords",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 37,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 1,
        paidCompetitors: 0,
      },
      {
        keyword: "free copy generator",
        topRankedUrl: "https://promoterkit.com/tools/ai/writer",
        rank: 58,
        rankChange: -14,
        searchVolume: 55,
        rankingHomepages: 13,
        paidCompetitors: 5,
      },
      {
        keyword: "content writing generator",
        topRankedUrl: "https://promoterkit.com/tools/ai/writer",
        rank: 34,
        rankChange: -3,
        searchVolume: 55,
        rankingHomepages: 12,
        paidCompetitors: 15,
      },
      {
        keyword: "backlink analyzer",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 43,
        rankChange: 1,
        searchVolume: 55,
        rankingHomepages: 3,
        paidCompetitors: 0,
      },
      {
        keyword: "best seo report generator",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 74,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 9,
        paidCompetitors: 0,
      },
      {
        keyword: "seo online analyzer",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 34,
        rankChange: 1,
        searchVolume: 55,
        rankingHomepages: 16,
        paidCompetitors: 1,
      },
      {
        keyword: "malicious email checker",
        topRankedUrl: "https://promoterkit.com/tools/email/checker",
        rank: 70,
        rankChange: 13,
        searchVolume: 55,
        rankingHomepages: 7,
        paidCompetitors: 6,
      },
      {
        keyword: "email extractor free online",
        topRankedUrl: "https://promoterkit.com/tools/email/text-extraction",
        rank: 31,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 4,
        paidCompetitors: 0,
      },
      {
        keyword: "free seo analysis report online",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 43,
        rankChange: 5,
        searchVolume: 55,
        rankingHomepages: 8,
        paidCompetitors: 0,
      },
      {
        keyword: "youtube ranking tools",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 53,
        rankChange: null,
        searchVolume: 55,
        rankingHomepages: 6,
        paidCompetitors: 0,
      },
      {
        keyword: "free seo website analyzer",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 34,
        rankChange: 2,
        searchVolume: 60,
        rankingHomepages: 11,
        paidCompetitors: 7,
      },
      {
        keyword: "free seo report generator",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 43,
        rankChange: -15,
        searchVolume: 60,
        rankingHomepages: 8,
        paidCompetitors: 6,
      },
      {
        keyword: "website analysis seo tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 70,
        rankChange: 14,
        searchVolume: 60,
        rankingHomepages: 10,
        paidCompetitors: 6,
      },
      {
        keyword: "free seo analysis tool online",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 37,
        rankChange: -1,
        searchVolume: 60,
        rankingHomepages: 10,
        paidCompetitors: 2,
      },
      {
        keyword: "website keyword checker tool",
        topRankedUrl:
          "https://promoterkit.com/tools/seo/website-keywords-checker",
        rank: 77,
        rankChange: -58,
        searchVolume: 60,
        rankingHomepages: 9,
        paidCompetitors: 0,
      },
      {
        keyword: "seo analysis free online",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 38,
        rankChange: -7,
        searchVolume: 60,
        rankingHomepages: 12,
        paidCompetitors: 0,
      },
      {
        keyword: "email bounce checker free",
        topRankedUrl: "https://promoterkit.com/tools/email/bulk-verifier",
        rank: 40,
        rankChange: -4,
        searchVolume: 65,
        rankingHomepages: 28,
        paidCompetitors: 2,
      },
      {
        keyword: "free keyword tool youtube",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 18,
        rankChange: -3,
        searchVolume: 70,
        rankingHomepages: 1,
        paidCompetitors: 4,
      },
      {
        keyword: "youtube account search",
        topRankedUrl: "https://promoterkit.com/tools/youtube/channel-search",
        rank: 74,
        rankChange: -7,
        searchVolume: 70,
        rankingHomepages: 9,
        paidCompetitors: 0,
      },
      {
        keyword: "youtube account finder",
        topRankedUrl: "https://promoterkit.com/tools/youtube/channel-search",
        rank: 59,
        rankChange: -49,
        searchVolume: 70,
        rankingHomepages: 9,
        paidCompetitors: 0,
      },
      {
        keyword: "check site backlinks",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 35,
        rankChange: 3,
        searchVolume: 70,
        rankingHomepages: 4,
        paidCompetitors: 0,
      },
      {
        keyword: "extract email online",
        topRankedUrl: "https://promoterkit.com/tools/email/text-extraction",
        rank: 36,
        rankChange: -24,
        searchVolume: 70,
        rankingHomepages: 7,
        paidCompetitors: 1,
      },
      {
        keyword: "rewrite a paragraph generator",
        topRankedUrl: "https://promoterkit.com/tools/ai/paragraph-rewriter",
        rank: 65,
        rankChange: -2,
        searchVolume: 70,
        rankingHomepages: 25,
        paidCompetitors: 4,
      },
      {
        keyword: "youtube top keywords",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 95,
        rankChange: -7,
        searchVolume: 70,
        rankingHomepages: 2,
        paidCompetitors: 2,
      },
      {
        keyword: "free backlink checkers",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 37,
        rankChange: null,
        searchVolume: 70,
        rankingHomepages: 2,
        paidCompetitors: 0,
      },
      {
        keyword: "blogger privacy policy generator",
        topRankedUrl:
          "https://promoterkit.com/tools/web/privacy-policy-generator",
        rank: 86,
        rankChange: -32,
        searchVolume: 70,
        rankingHomepages: 8,
        paidCompetitors: 0,
      },
      {
        keyword: "bulk email verifier online",
        topRankedUrl: "https://promoterkit.com/tools/email/bulk-verifier",
        rank: 21,
        rankChange: 8,
        searchVolume: 70,
        rankingHomepages: 22,
        paidCompetitors: 16,
      },
      {
        keyword: "backlinks tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 32,
        rankChange: 5,
        searchVolume: 70,
        rankingHomepages: 4,
        paidCompetitors: 4,
      },
      {
        keyword: "free website analyzer seo",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 52,
        rankChange: -10,
        searchVolume: 70,
        rankingHomepages: 12,
        paidCompetitors: 9,
      },
      {
        keyword: "youtube seo generator",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 31,
        rankChange: -7,
        searchVolume: 70,
        rankingHomepages: 4,
        paidCompetitors: 2,
      },
      {
        keyword: "bad backlink checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 49,
        rankChange: -3,
        searchVolume: 70,
        rankingHomepages: 3,
        paidCompetitors: 3,
      },
      {
        keyword: "best youtube name generator",
        topRankedUrl: "https://promoterkit.com/tools/youtube/name-generator",
        rank: 37,
        rankChange: null,
        searchVolume: 70,
        rankingHomepages: 2,
        paidCompetitors: 1,
      },
      {
        keyword: "free seo site checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 51,
        rankChange: -9,
        searchVolume: 70,
        rankingHomepages: 14,
        paidCompetitors: 1,
      },
      {
        keyword: "free keywords generator",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 75,
        rankChange: 0,
        searchVolume: 70,
        rankingHomepages: 15,
        paidCompetitors: 1,
      },
      {
        keyword: "bulk keyword difficulty checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/bulk-keyword-tool",
        rank: 23,
        rankChange: 0,
        searchVolume: 70,
        rankingHomepages: 5,
        paidCompetitors: 0,
      },
      {
        keyword: "keyword page checker",
        topRankedUrl:
          "https://promoterkit.com/tools/seo/website-keywords-checker",
        rank: 52,
        rankChange: null,
        searchVolume: 70,
        rankingHomepages: 6,
        paidCompetitors: 0,
      },
      {
        keyword: "free seo analyzer tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 38,
        rankChange: -4,
        searchVolume: 75,
        rankingHomepages: 11,
        paidCompetitors: 4,
      },
      {
        keyword: "seo page analyzer tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 63,
        rankChange: -11,
        searchVolume: 80,
        rankingHomepages: 11,
        paidCompetitors: 0,
      },
      {
        keyword: "seo analysis free tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 40,
        rankChange: 0,
        searchVolume: 80,
        rankingHomepages: 10,
        paidCompetitors: 1,
      },
      {
        keyword: "email list checker free",
        topRankedUrl: "https://promoterkit.com/tools/email/bulk-verifier",
        rank: 31,
        rankChange: null,
        searchVolume: 80,
        rankingHomepages: 26,
        paidCompetitors: 2,
      },
      {
        keyword: "free online tools to write content",
        topRankedUrl: "https://promoterkit.com/tools/ai/writer",
        rank: 84,
        rankChange: -35,
        searchVolume: 80,
        rankingHomepages: 7,
        paidCompetitors: 11,
      },
      {
        keyword: "content writing tools free",
        topRankedUrl: "https://promoterkit.com/tools/ai/writer",
        rank: 75,
        rankChange: 0,
        searchVolume: 80,
        rankingHomepages: 3,
        paidCompetitors: 0,
      },
      {
        keyword: "youtube backlink checker",
        topRankedUrl: "https://promoterkit.com/tools/seo/backlinks-checker",
        rank: 48,
        rankChange: 27,
        searchVolume: 80,
        rankingHomepages: 1,
        paidCompetitors: 0,
      },
      {
        keyword: "seo site analyzer tool",
        topRankedUrl: "https://promoterkit.com/tools/seo/",
        rank: 28,
        rankChange: -5,
        searchVolume: 80,
        rankingHomepages: 11,
        paidCompetitors: 3,
      },
      {
        keyword: "youtube keywords analytics",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 37,
        rankChange: 23,
        searchVolume: 80,
        rankingHomepages: 2,
        paidCompetitors: 7,
      },
      {
        keyword: "find keywords for youtube",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 35,
        rankChange: null,
        searchVolume: 80,
        rankingHomepages: 2,
        paidCompetitors: 0,
      },
      {
        keyword: "privacy policy link generator",
        topRankedUrl:
          "https://promoterkit.com/tools/web/privacy-policy-generator",
        rank: 79,
        rankChange: 1,
        searchVolume: 80,
        rankingHomepages: 8,
        paidCompetitors: 5,
      },
      {
        keyword: "keyword tool for youtube",
        topRankedUrl: "https://promoterkit.com/tools/youtube/keyword-tool",
        rank: 17,
        rankChange: 2,
        searchVolume: 80,
        rankingHomepages: 3,
        paidCompetitors: 4,
      },
      {
        keyword: "email address checker free",
        topRankedUrl: "https://promoterkit.com/tools/email/checker",
        rank: 62,
        rankChange: -13,
        searchVolume: 80,
        rankingHomepages: 25,
        paidCompetitors: 7,
      },
      {
        keyword: "email title generator",
        topRankedUrl: "https://promoterkit.com/tools/email/subject-line-tester",
        rank: 94,
        rankChange: -14,
        searchVolume: 80,
        rankingHomepages: 2,
        paidCompetitors: 1,
      },
      {
        keyword: "generate terms and conditions free",
        topRankedUrl: "https://promoterkit.com/tools/web/terms-generator",
        rank: 41,
        rankChange: -6,
        searchVolume: 80,
        rankingHomepages: 14,
        paidCompetitors: 1,
      },
      {
        keyword: "bulk keyword analyzer",
        topRankedUrl: "https://promoterkit.com/tools/seo/bulk-keyword-tool",
        rank: 12,
        rankChange: -2,
        searchVolume: 80,
        rankingHomepages: 10,
        paidCompetitors: 2,
      },
    ],
    keywordsCount: 100,
    message: "Success",
  },
};
module.exports.keywordsByWebsite = keywordsByWebsite;
